name: JRuby CI

on: [push]

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ 8, 11]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: test profile
      run: mvn -B clean package -Ptest
    - name: main profile
      run: mvn -B clean package -Pmain
    - name: dist profile
      run: mvn -B clean package -Pdist
    - name: jruby-jars profile
      run: mvn -B clean package -Pjruby-jars
    - name: complete profile
      run: mvn -B clean package -Pcomplete
    - name: osgi profile
      run: mvn -B clean package -Posgi
    - name: jruby-jars extended
      run: mvn -B clean package -Pjruby-jars,test -Dinvoker.test=extended
    - name: main extended
      run: mvn -B clean package -Pmain,test -Dinvoker.test=extended
    - name: dependency convergence
      run: mvn -B -Pmain -Dinvoker.test=GH-6081* integration-test
