name: JRuby CI

on: [push]

jobs:
  maven-test-8:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: test profile
      run: mvn -B clean package -Ptest
    - name: main profile
      run: mvn -B clean package -Pmain
    - name: dist profile
      run: mvn -B clean package -Pdist
    - name: jruby-jars profile
      run: mvn -B clean package -Pjruby-jars
    - name: complete profile
      run: mvn -B clean package -Pcomplete
    - name: osgi profile
      run: mvn -B clean package -Posgi
    - name: jruby-jars extended
      run: mvn -B clean package -Pjruby-jars,test -Dinvoker.test=extended
    - name: main extended
      run: mvn -B clean package -Pmain,test -Dinvoker.test=extended
    - name: dependency convergence
      run: mvn -B -Pmain -Dinvoker.test=GH-6081* integration-test

  maven-test-11:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: main profile
        run: mvn -B clean package -Pmain
      - name: dist profile
        run: mvn -B clean package -Pdist
      - name: complete profile
        run: mvn -B clean package -Pcomplete
      - name: osgi profile
        run: mvn -B clean package -Posgi
      - name: jruby-jars extended
        run: mvn -B clean package -Pjruby-jars,test -Dinvoker.test=extended
      - name: main extended
        run: mvn -B clean package -Pmain,test -Dinvoker.test=extended
